<?php

/**
 * Implements hook_menu().
 */
function ebay_partner_network_menu() {
  $items['admin/config/system/ebay_partner_network'] = array(
    'title' => 'Ebay Partner Network Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ebay_partner_network_admin_settings'),
    'access arguments' => array('administer ebay partner network settings'),
    'file' => 'ebay_partner_network.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function ebay_partner_network_permission() {
  return array(
    'administer ebay partner network settings' => array(
      'title' => t('Administer Ebay Partner Network Settings'),
      'description' => t('Administer Ebay Partner Network Settings.'),
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function ebay_partner_network_block_info() {
  $blocks['pn_related_ebay_items'] = array(
    'info' => t('Related ebay items.'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ebay_partner_network_block_view($delta = '') {

  $block = array();

  switch ($delta) {
    case 'pn_related_ebay_items':
      $app_id = variable_get('ebay_partner_network_app_id', '');
      if(!empty($app_id)) {
        $settings = array(
          'app_id' => $app_id,
          'items_num' => variable_get('ebay_partner_network_items_num', 5),
          'store_id' => variable_get('ebay_partner_network_store_id', 'EBAY-GB'),
          'campaign_id' => variable_get('ebay_partner_network_campaign_id', ''),
          'network_id' => variable_get('ebay_partner_network_network_id', 9),
          'custom_id' => variable_get('ebay_partner_network_custom_id', ''),
        );

        $settings['keyword'] = ebay_partner_network_get_kw();
        $settings['category'] = ebay_partner_network_get_category();

        $block['content'] = array(
          '#theme' => array('ebay_partner_network_block'),
          '#attached' => array(
            'js' => array(
               drupal_get_path('module', 'ebay_partner_network') . '/js/ebay.js',
               array('data' => array('ebay_partner_network' => $settings), 'type' => 'setting'),
            )
          )
        );
        $block['subject'] = t('Related Ebay Items');
      }
      break;
  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function ebay_partner_network_theme($existing, $type, $theme, $path) {
  return array(
    'ebay_partner_network_block' => array(
      'template' => 'ebay_partner_network_block',
      'path' => drupal_get_path('module', 'ebay_partner_network') . '/theme',
    ),
  );
}

/**
 * Returns a keyword to perform a search on eBay.
 * @return string
 */
function ebay_partner_network_get_kw() {
  $kw = '';

  $menu_object = menu_get_object();
  if (!empty($menu_object->title)) {
    $kw = $menu_object->title;
  }
  drupal_alter('ebay_partner_network_keyword', $kw);

  return $kw;
}

/**
 * Returns a category ID where eBay search will be performed.
 * @return int
 */
function ebay_partner_network_get_category() {
  $category = '';
  drupal_alter('ebay_partner_network_category', $category);
  $category = empty($category) ? variable_get('ebay_partner_network_default_category', -1) : $category;
  return $category;
}

/**
 * Get Category List from Ebay
 * @param unknown_type $app_id
 */
function ebay_partner_network_get_categories($app_id) {
  $categories = array();
  $site = variable_get('ebay_partner_network_store_id', 'EBAY-GB');
  $site_id = ebay_partner_network_site_ids($site);
  if(!empty($site_id)) {
    $url = 'http://open.api.ebay.com/Shopping?callname=GetCategoryInfo&appid=' . $app_id . '&siteid=' . $site_id . '&CategoryID=-1&version=729&IncludeSelector=ChildCategories';
    $cat_list = file_get_contents($url);
    $xml = simplexml_load_string($cat_list);
    if(!empty($xml->CategoryArray->Category)) {
      foreach ($xml->CategoryArray->Category as $cat) {
        $categories[(string)$cat->CategoryID] = (string)$cat->CategoryName;
      }
    }
  }
  return $categories;
}

function ebay_partner_network_options_list($field, $instance, $entity_type, $entity) {
  $options = array();
  $app_id = variable_get('ebay_partner_network_app_id','');
  if(!empty($app_id)) {
    $options = ebay_partner_network_get_categories($app_id);
  }
  return $options;
}



function ebay_partner_network_field_info() {
  return array(
    'ebay_category' => array(
      'label' => t('Ebay Category'),
      'description' => t('Ebay Category.'),
      'settings' => array('max_length' => 255),
      'instance_settings' => array(
        'text_processing' => 0,
      ),
      'default_widget' => 'options_select',
      'default_formatter' => 'states_field_options',
    ),
  );
}



function ebay_partner_network_field_widget_info_alter(&$info) {
  $widgets = array(
    'options_select' => array('ebay_category'),
  );
  foreach ($widgets as $widget => $field_types) {
    $info[$widget]['field types'] = array_merge($info[$widget]['field types'], $field_types);
  }
}

/**
 * Implements hook_field_is_empty().
 */
function ebay_partner_network_field_is_empty($item, $field) {
  return false;
}

/**
 * Returns all fields which have a type of 'ebay_category'
 */
function ebay_partner_network_category_fields() {
  $cache_bin = 'cache_field';
  $cache_key = 'field_info:ebay_partner_categories';
  if ($cache = cache_get($cache_key, $cache_bin)) {
    $category_fields = $cache->data;
  }
  else {
    $category_fields = field_read_fields(array('type' => 'ebay_category'));
    if(!empty($category_fields)) {
      cache_set($cache_key, $category_fields, $cache_bin);
    }
  }
 return $category_fields;
}

/**
 * Returns site_id by name
 * @param unknown_type $site
 */
function ebay_partner_network_site_ids($site = null) {
  $sites = array(
    'EBAY-US' => 0,
    'EBAY-ENCA' => 2,
    'EBAY-GB' => 3,
    'EBAY-AU' => 15,
    'EBAY-AT' => 16,
    'EBAY-FRBE' => 23,
    'EBAY-FR' => 71,
    'EBAY-DE' => 77,
    'EBAY-MOTOR' => 100,
    'EBAY-IT' => 101,
    'EBAY-NLBE' => 123,
    'EBAY-NL' => 146,
    'EBAY-ES' => 186,
    'EBAY-CH' => 193,
    'EBAY-HK' => 201,
    'EBAY-IN' => 203,
    'EBAY-IE' => 205,
    'EBAY-MY' => 207,
    'EBAY-FRCA' => 210,
    'EBAY-PH' => 211,
    'EBAY-PL' => 212,
    'EBAY-SG' => 216
  );
  return (!empty($site) && !empty($sites[$site])) ? $sites[$site] : $sites;
}