<?php

/**
 * Implements hook_field_schema().
 */
function ebay_partner_network_field_schema($field) {
  $schema = array();
  $schema['columns']['option'] = array(
    'type' => 'varchar',
    'length' => 25,
    'not null' => FALSE
  );
  return $schema;
}

/**
 * Implements hook_install().
 */
function ebay_partner_network_install() {

}

/**
 * Implements hook_uninstall().
 */
function ebay_partner_network_uninstall() {

}